### ISSUE TITLE
kubectlImage undefined

### ISSUE THREAD

**Issue by mechinn** [truecharts/library-charts#256]
### App Name

traefik

### SCALE Version

22.02.3

### App Version

2.9.1_13.4.11

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
N/A
```

### Application Configuration

N/A

### Describe the bug

Unable to install traefik due to missing values in library-charts for `.Values.kubectlImage` when `.Values.updateCRD` used by a chart

### To Reproduce

Attempt to install with default settings and `traefik` name

```
    Application Name: traefik
    Version: 13.4.11
    :
        Show Advanced Controller Settings: false
        Show Expert Configuration Options: false
    Extra Args: false
    Timezone: 'America/New_York' timezone
    Show Expert Configuration: false
    ingressClass:
        Enable: false
    Logs:
        General Logs:
            Log Level: Errors
            General Log format: Common Log Format
        Access Logs:
            Enable: false
    Configure Service Entrypoint:
        Main Service:
            Service Type: LoadBalancer (Expose Ports)
            LoadBalancer IP:
            Show Advanced Service Settings: false
            Service's Port(s) Configuration:
                Main Entrypoint Configuration:
                    Show Advanced Settings: false
                    Entrypoints Port: 9000
        TCP Service:
            Service Type: LoadBalancer (Expose Ports)
            LoadBalancer IP:
            Show Advanced Service Settings: false
            Service's Port(s) Configuration:
                web Entrypoint Configuration:
                    Entrypoints Port: 9080
                    Show Advanced Settings: false
                    Accept Forwarded Headers:
                        Enable: false
                    Accept Proxy Protocol connections:
                        Enable: false
                websecure Entrypoints Configuration:
                    Entrypoints Port: 9443
                    Show Advanced Settings: false
                    Accept Forwarded Headers:
                        Enable: false
                    Accept Proxy Protocol connections:
                        Enable: false
    :
        Main Ingress:
            Enable Ingress: false
            Show Expert Configuration Options: false
    Container Security Settings:
        Change PUID / UMASK values: false
    Show Advanced Security Settings: false
    Pod Security Context:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        When should we take ownership?: OnRootMismatch
    Set Custom Resource Limits/Requests (Advanced): false
    :
        Codeserver:
            Enabled: false
            :
                LoadBalancer IP: 
        Promtail:
            Enabled: false
        Netshoot:
            Enabled: false
        VPN:
            Type: disabled
    Please read the documentation at https://truecharts.org:
        I have checked the documentation: true

Confirm these settings. 
```

### Expected Behavior

Able to install traefik

### Screenshots

N/A

### Additional Context

```
Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 411, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 446, in __run_body
    rv = await self.method(*([self] + args))
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1140, in nf
    res = await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1272, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 481, in do_create
    await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1344, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1304, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1205, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 44, in helm_action
    raise CallError(f'Failed to {tn_action} chart release: {stderr.decode()}')
middlewared.service_exception.CallError: [EFAULT] Failed to install chart release: Error: INSTALLATION FAILED: failed pre-install: warning: Hook pre-install traefik/templates/common.yaml failed: Job.batch "traefik-crds" is invalid: [spec.template.spec.containers[0].image: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "crds"]
```

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Good catch!
Weird that out CI didnt catch this :/

**Comment by Ornias1993** [comment]
fixed
